server.port: 9999

spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: document-service-route
              uri: lb://document-service
              predicates:
                - Path=/api/v1/documents/**
                - Method=GET,POST,PUT,DELETE,OPTIONS
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
                - Method=GET,POST,PUT,DELETE,OPTIONS

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/


