server:
  port: 8082

spring:
  application:
    name: aiservice
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
